changed the gem to work with globalized site
TerraCycleUS/omniauth-terracycle pull request #1
Opened 2019-03-25 11:03 UTC by SkayHUN

2019-04-01 08:11 UTC, storhet requested changes
Update README.md the Configuration part based on this changes

2019-04-01 09:28 UTC, erik-terracycle approved these changes

2019-04-08 10:41 UTC, bluta approved these changes

2019-04-08 11:43 UTC, bluta approved these changes

2019-04-08 11:43 UTC, merged